Improve Linux memory collection with AVLM
diogo-fernan/ir-rescue pull request #19
Opened 2020-12-04 15:42 UTC by mczap

Linpmem read /proc/kcore during my tests, but never completed the dump, but filled the partition. Tested with CentOS, Ubuntu and RHEL VMs.

Of all the tools I looked at as replacement, AVML proved to be the easiest to use. Compiled as described, on an Ubuntu 18.04.5 LTS VM. The binary should run on many systems and kernel versions.
https://github.com/microsoft/avml#building-on-ubuntu
https://github.com/microsoft/avml#tested-distributions

2020-12-06 15:24 UTC, diogo-fernan commented on nix/tools-nix/mem/readme.md
> +AVML compiled as described, on an Ubuntu 18.04.5 LTS VM. The binary should run on many systems and kernel versions.
Perhaps this whole description can rather go into the main `README.md` file?

2020-12-06 15:25 UTC, diogo-fernan commented on README.md
> +* **AVML-0.21** (Acquire Volatile Memory for Linux): [AVML](https://github.com/microsoft/avml) is an X86_64 userland volatile memory acquisition tool written in Rust, intended to be deployed as a sta
Here the building information can be appended.

2020-12-06 15:26 UTC, diogo-fernan requested changes
Would you mind merging the memory-specific `README.md` file with the generic one?

I can update the change history and the configuration file afterwards to reflect these changes.

2020-12-07 15:43 UTC, mczap commented
Thank you for your quick reaction and open-mindedness towards my suggestions. I have changed the [readme.md](https://github.com/mczap/ir-rescue/blob/memory-collection-AVML/README.md) as you recommended it and deleted the superfluous one under ./nix/tools-nix/mem/.
Now I have to find out how to set the execution bit via git and your script will be even easier to use. Thanks for your development work

2020-12-08 10:51 UTC, mczap commented
I have done all the needed changes, is it OK for you to merge it, or would you like further changes?

2020-12-09 15:21 UTC, mczap commented
On RHEL7 there are still problems with archiving after the collection. In the script there is also a reference to the aff4 file, witch I missed. Please don't merge yet. I try to solve these points first.

2020-12-14 13:30 UTC, diogo-fernan commented
Cool, thanks for contributing! Merging now.

2020-12-14 13:30 UTC, merged